spring.application.name=Prime
spring.config.import=optional:file:./.env[.properties]

## MySQL configs
spring.datasource.url=jdbc:mysql://localhost:3306/auto_prime
spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}

## JPA configs
spring.jpa.hibernate.ddl-auto=create
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.session.jdbc.initialize-schema=always


## JWT configs
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
